### ISSUE TITLE
Switching to linear gradient works but raises error

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#103]
<img width="293" alt="screen shot 2016-12-29 at 4 49 41 pm" src="https://cloud.githubusercontent.com/assets/467450/21557847/df4d2a5c-cde6-11e6-9ca6-3d687fee48da.png">

```
gradient-editor.js:1117 Uncaught (in promise) TypeError: self.target.fill.vectorAsAngle is not a function
    at Ellipse.relayout (http://localhost:9011/lively.morphic/ide/styling/gradient-editor.js:1117:112)
    at GradientDirectionHandle_relayout_ (http://localhost:9011/lively.morphic/ide/styling/gradient-editor.js:1099:48)
    at GradientDirectionHandle_build_ (http://localhost:9011/lively.morphic/ide/styling/gradient-editor.js:1106:34)
    at GradientDirectionHandle_initialize_ (http://localhost:9011/lively.morphic/ide/styling/gradient-editor.js:1060:34)
    at new GradientDirectionHandle (http://localhost:9011/lively.morphic/ide/styling/gradient-editor.js:1047:72)
    at GradientEditor._callee3$ (http://localhost:9011/lively.morphic/ide/styling/gradient-editor.js:344:71)
    at tryCatch (http://localhost:9011/lively.modules/dist/lively.modules.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:9011/lively.modules/dist/lively.modules.js:331:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:9011/lively.modules/dist/lively.modules.js:96:21)
    at step (http://localhost:9011/lively.modules/node_modules/systemjs-plugin-babel/babel-helpers/asyncToGenerator.js:13:36)
﻿```

**Comment by merryman** [comment]
Forgot to push a change in lively.graphics. That should be fixed now.
