### ISSUE TITLE
Halo for ellipse broken

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#112]
looks like 56eda17 broke ellipse halo activation

```
Uncaught Error: Error in event handler <HaloItem - style>.onMouseDown: TypeError: Cannot read property 'active' of null
    at Ellipse.update (http://localhost:9011/lively.morphic/halo/stylization.js:446:51)
    at StyleHalo_relayout_.controls.submorphs.forEach.s (http://localhost:9011/lively.morphic/halo/stylization.js:285:61)
    at Array.forEach (native)
```

**Comment by merryman** [comment]
This is already fixed locally. Will push!
