### ISSUE TITLE
[halos] resize error

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#78]
```
EventDispatcher.js:499 Uncaught Error: Error in event handler <HaloItem - resize>.onDrag: TypeError: this.localize(...).extent(...).scaleRectTo is not a function
    at Halo_toggleDiagonal_ (http://localhost:9001/node_modules/lively.morphic/halo/morph.js:1148:92)
    at HaloItem.proportionalMode (http://localhost:9001/node_modules/lively.morphic/halo/morph.js:613:46)
    at HaloItem.update (http://localhost:9001/node_modules/lively.morphic/halo/morph.js:554:50)
    at HaloItem.onDrag (http://localhost:9001/node_modules/lively.morphic/halo/morph.js:593:42)
    at EventDispatcher_dispatchEvent_ (http://localhost:9001/node_modules/lively.morphic/events/EventDispatcher.js:497:64)
    at eval (http://localhost:9001/node_modules/lively.morphic/events/EventDispatcher.js:550:47)
    at Array.forEach (native)
    at EventDispatcher_dispatchDOMEvent_ (http://localhost:9001/node_modules/lively.morphic/events/EventDispatcher.js:549:36)
    at fn (http://localhost:9001/node_modules/lively.morphic/events/EventDispatcher.js:288:51)
    at Object.dispatchEvent (http://localhost:9001/node_modules/lively.morphic/node_modules/pepjs/dist/pep.js:502:18)
```

**Comment by merryman** [comment]
Looks like you need to update lively.graphics ?

**Comment by rksm** [comment]
Ahhh, sorry.
