### ISSUE TITLE
color choose not working

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.morphic#99]
<img width="222" alt="screen shot 2016-12-29 at 4 43 23 pm" src="https://cloud.githubusercontent.com/assets/467450/21557784/0f0f8c18-cde6-11e6-9a9b-f70435e6f201.png">

Clicking on the color chooser circle raises an error:

```
window.js:132 Uncaught (in promise) TypeError: Cannot read property 'bounds' of undefined
    at ColorPicker.Window_relayoutWindowControls_ (http://localhost:9011/lively.morphic/window.js:132:181)
    at ColorPicker.set (http://localhost:9011/lively.morphic/window.js:110:34)
    at ColorPicker.Window_initialize_ (http://localhost:9011/lively.morphic/window.js:81:50)
    at ColorPicker_initialize_ (http://localhost:9011/lively.morphic/ide/styling/color-picker.js:317:177)
    at new ColorPicker (http://localhost:9011/lively.morphic/ide/styling/color-picker.js:309:72)
    at ColorPickerField._callee$ (http://localhost:9011/lively.morphic/ide/styling/color-picker.js:226:64)
    at tryCatch (http://localhost:9011/lively.modules/dist/lively.modules.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:9011/lively.modules/dist/lively.modules.js:331:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:9011/lively.modules/dist/lively.modules.js:96:21)
    at step (http://localhost:9011/lively.modules/node_modules/systemjs-plugin-babel/babel-helpers/asyncToGenerator.js:13:36)
```

**Comment by rksm** [comment]
This seems to be fixed but see #105
